export type UserType = {
    id: number;
    name: string;
    email: string;
    gender: string;
    Occupation: string;
    favorite: string;
    ip_address: string;
};
export const users: UserType[] = [
    {
        id: 1,
        name: 'Wyatan MacAskill',
        email: 'wmacaskill0@usgs.gov',
        gender: 'Male',
        Occupation: 'Social Worker',
        favorite: 'Goldenrod',
        ip_address: '133.221.155.205',
    },
    {
        id: 2,
        name: 'Jorge Fathers',
        email: 'jfathers1@reddit.com',
        gender: 'Male',
        Occupation: 'Systems Administrator III',
        favorite: 'Yellow',
        ip_address: '224.11.100.78',
    },
    {
        id: 3,
        name: 'Catha Coverley',
        email: 'ccoverley2@msn.com',
        gender: 'Female',
        Occupation: 'Database Administrator III',
        favorite: 'Maroon',
        ip_address: '182.207.19.191',
    },
    {
        id: 4,
        name: 'Dev Pauleau',
        email: 'dpauleau3@mashable.com',
        gender: 'Male',
        Occupation: 'Software Engineer I',
        favorite: 'Crimson',
        ip_address: '81.24.74.206',
    },
    {
        id: 5,
        name: 'Ryun Rosenblum',
        email: 'rrosenblum4@microsoft.com',
        gender: 'Male',
        Occupation: 'Web Designer IV',
        favorite: 'Green',
        ip_address: '231.238.11.98',
    },
    {
        id: 6,
        name: 'Davita Bleier',
        email: 'dbleier5@berkeley.edu',
        gender: 'Female',
        Occupation: 'Analyst Programmer',
        favorite: 'Pink',
        ip_address: '95.250.162.210',
    },
    {
        id: 7,
        name: 'Raye Asbrey',
        email: 'rasbrey6@taobao.com',
        gender: 'Female',
        Occupation: 'Research Assistant IV',
        favorite: 'Puce',
        ip_address: '230.136.68.194',
    },
    {
        id: 8,
        name: 'Corry Clemanceau',
        email: 'cclemanceau7@weather.com',
        gender: 'Female',
        Occupation: 'Marketing Assistant',
        favorite: 'Fuscia',
        ip_address: '249.10.203.179',
    },
    {
        id: 9,
        name: 'Ange Baugham',
        email: 'abaugham8@google.de',
        gender: 'Male',
        Occupation: 'Research Nurse',
        favorite: 'Blue',
        ip_address: '137.74.24.239',
    },
    {
        id: 10,
        name: 'Raimundo Cogswell',
        email: 'rcogswell9@ezinearticles.com',
        gender: 'Male',
        Occupation: 'Environmental Tech',
        favorite: 'Aquamarine',
        ip_address: '132.15.71.73',
    },
    {
        id: 11,
        name: 'Devin Landells',
        email: 'dlandellsa@lulu.com',
        gender: 'Male',
        Occupation: 'Staff Scientist',
        favorite: 'Goldenrod',
        ip_address: '186.104.129.101',
    },
    {
        id: 12,
        name: 'Gothart Cuniam',
        email: 'gcuniamb@youtu.be',
        gender: 'Genderqueer',
        Occupation: 'Editor',
        favorite: 'Green',
        ip_address: '18.56.158.172',
    },
    {
        id: 13,
        name: 'Penelopa Metcalfe',
        email: 'pmetcalfec@baidu.com',
        gender: 'Female',
        Occupation: 'Senior Financial Analyst',
        favorite: 'Indigo',
        ip_address: '100.0.122.39',
    },
    {
        id: 14,
        name: 'Silvan Issac',
        email: 'sissacd@mashable.com',
        gender: 'Male',
        Occupation: 'VP Marketing',
        favorite: 'Pink',
        ip_address: '115.59.8.166',
    },
    {
        id: 15,
        name: 'Harriet Koppe',
        email: 'hkoppee@ihg.com',
        gender: 'Female',
        Occupation: 'GIS Technical Architect',
        favorite: 'Yellow',
        ip_address: '57.165.8.187',
    },
    {
        id: 16,
        name: 'Bartlet Broomfield',
        email: 'bbroomfieldf@java.com',
        gender: 'Male',
        Occupation: 'Human Resources Assistant III',
        favorite: 'Goldenrod',
        ip_address: '18.12.66.138',
    },
    {
        id: 17,
        name: 'Pet Wegener',
        email: 'pwegenerg@va.gov',
        gender: 'Agender',
        Occupation: 'Help Desk Technician',
        favorite: 'Teal',
        ip_address: '255.145.225.58',
    },
    {
        id: 18,
        name: 'Hughie Outright',
        email: 'houtrighth@sciencedaily.com',
        gender: 'Male',
        Occupation: 'Electrical Engineer',
        favorite: 'Purple',
        ip_address: '159.27.34.243',
    },
    {
        id: 19,
        name: 'Brantley Zannini',
        email: 'bzanninii@nsw.gov.au',
        gender: 'Male',
        Occupation: 'Chief Design Engineer',
        favorite: 'Pink',
        ip_address: '199.31.238.76',
    },
    {
        id: 20,
        name: 'Eadith Beaulieu',
        email: 'ebeaulieuj@nifty.com',
        gender: 'Female',
        Occupation: 'Nurse',
        favorite: 'Blue',
        ip_address: '52.250.248.50',
    },
    {
        id: 21,
        name: 'Fiona Vinsen',
        email: 'fvinsenk@irs.gov',
        gender: 'Female',
        Occupation: 'Senior Sales Associate',
        favorite: 'Pink',
        ip_address: '198.211.44.190',
    },
    {
        id: 22,
        name: 'Sutherlan Colloby',
        email: 'scollobyl@yellowbook.com',
        gender: 'Male',
        Occupation: 'Financial Advisor',
        favorite: 'Red',
        ip_address: '254.138.160.138',
    },
    {
        id: 23,
        name: 'Silvia Sigars',
        email: 'ssigarsm@ycombinator.com',
        gender: 'Female',
        Occupation: 'Food Chemist',
        favorite: 'Teal',
        ip_address: '232.232.35.0',
    },
    {
        id: 24,
        name: 'Davis Krauze',
        email: 'dkrauzen@tmall.com',
        gender: 'Male',
        Occupation: 'Assistant Professor',
        favorite: 'Red',
        ip_address: '226.152.183.209',
    },
    {
        id: 25,
        name: 'Dodie Molfino',
        email: 'dmolfinoo@arstechnica.com',
        gender: 'Female',
        Occupation: 'Compensation Analyst',
        favorite: 'Yellow',
        ip_address: '51.206.131.214',
    },
    {
        id: 26,
        name: 'Cassius Comiskey',
        email: 'ccomiskeyp@histats.com',
        gender: 'Male',
        Occupation: 'Accounting Assistant III',
        favorite: 'Pink',
        ip_address: '127.104.89.37',
    },
    {
        id: 27,
        name: 'Irvin Roux',
        email: 'irouxq@facebook.com',
        gender: 'Male',
        Occupation: 'Design Engineer',
        favorite: 'Puce',
        ip_address: '19.78.148.217',
    },
    {
        id: 28,
        name: 'Jordanna Whitney',
        email: 'jwhitneyr@aboutads.info',
        gender: 'Female',
        Occupation: 'Occupational Therapist',
        favorite: 'Turquoise',
        ip_address: '223.58.54.39',
    },
    {
        id: 29,
        name: 'Chuck Malden',
        email: 'cmaldens@kickstarter.com',
        gender: 'Male',
        Occupation: 'Executive Secretary',
        favorite: 'Green',
        ip_address: '138.221.23.13',
    },
    {
        id: 30,
        name: 'Vinny Cauthra',
        email: 'vcauthrat@ftc.gov',
        gender: 'Female',
        Occupation: 'Structural Analysis Engineer',
        favorite: 'Green',
        ip_address: '121.182.152.85',
    },
    {
        id: 31,
        name: 'Ferrell Hedling',
        email: 'fhedlingu@discuz.net',
        gender: 'Male',
        Occupation: 'Analog Circuit Design manager',
        favorite: 'Yellow',
        ip_address: '48.66.25.43',
    },
    {
        id: 32,
        name: 'Ody Blais',
        email: 'oblaisv@1und1.de',
        gender: 'Bigender',
        Occupation: 'Cost Accountant',
        favorite: 'Khaki',
        ip_address: '243.177.246.150',
    },
    {
        id: 33,
        name: 'Osborne Titcom',
        email: 'otitcomw@guardian.co.uk',
        gender: 'Male',
        Occupation: 'Research Assistant III',
        favorite: 'Yellow',
        ip_address: '248.226.198.104',
    },
    {
        id: 34,
        name: 'Roobbie Dunhill',
        email: 'rdunhillx@businessweek.com',
        gender: 'Female',
        Occupation: 'Nurse Practicioner',
        favorite: 'Yellow',
        ip_address: '129.116.84.201',
    },
    {
        id: 35,
        name: 'Lurleen Rodden',
        email: 'lroddeny@list-manage.com',
        gender: 'Female',
        Occupation: 'Civil Engineer',
        favorite: 'Teal',
        ip_address: '46.36.103.100',
    },
    {
        id: 36,
        name: 'Shanan Szymoni',
        email: 'sszymoniz@godaddy.com',
        gender: 'Male',
        Occupation: 'Health Coach III',
        favorite: 'Violet',
        ip_address: '205.238.255.216',
    },
    {
        id: 37,
        name: 'Evaleen Cratchley',
        email: 'ecratchley10@rediff.com',
        gender: 'Bigender',
        Occupation: 'Marketing Assistant',
        favorite: 'Turquoise',
        ip_address: '82.219.183.152',
    },
    {
        id: 38,
        name: 'Rori Aps',
        email: 'raps11@mediafire.com',
        gender: 'Female',
        Occupation: 'Staff Accountant IV',
        favorite: 'Yellow',
        ip_address: '21.22.199.148',
    },
    {
        id: 39,
        name: 'Cherie Licence',
        email: 'clicence12@wikipedia.org',
        gender: 'Female',
        Occupation: 'Electrical Engineer',
        favorite: 'Khaki',
        ip_address: '112.155.13.177',
    },
    {
        id: 40,
        name: 'Lambert Jutson',
        email: 'ljutson13@cbslocal.com',
        gender: 'Male',
        Occupation: 'Computer Systems Analyst IV',
        favorite: 'Blue',
        ip_address: '233.182.141.65',
    },
    {
        id: 41,
        name: 'Morgan Byer',
        email: 'mbyer14@exblog.jp',
        gender: 'Female',
        Occupation: 'Software Test Engineer I',
        favorite: 'Maroon',
        ip_address: '157.61.22.175',
    },
    {
        id: 42,
        name: 'Germain Placstone',
        email: 'gplacstone15@over-blog.com',
        gender: 'Female',
        Occupation: 'Media Manager II',
        favorite: 'Yellow',
        ip_address: '108.222.88.14',
    },
    {
        id: 43,
        name: 'Dinah Jeanequin',
        email: 'djeanequin16@vimeo.com',
        gender: 'Female',
        Occupation: 'Occupational Therapist',
        favorite: 'Puce',
        ip_address: '192.255.120.184',
    },
    {
        id: 44,
        name: 'Stephana Tremeer',
        email: 'stremeer17@prnewswire.com',
        gender: 'Female',
        Occupation: 'Clinical Specialist',
        favorite: 'Khaki',
        ip_address: '79.90.201.227',
    },
    {
        id: 45,
        name: 'Sascha Sawford',
        email: 'ssawford18@sciencedirect.com',
        gender: 'Female',
        Occupation: 'Structural Engineer',
        favorite: 'Mauv',
        ip_address: '92.179.129.211',
    },
    {
        id: 46,
        name: 'Eugenia Hyett',
        email: 'ehyett19@army.mil',
        gender: 'Genderqueer',
        Occupation: 'Staff Scientist',
        favorite: 'Red',
        ip_address: '188.112.42.135',
    },
    {
        id: 47,
        name: 'Huntington Ruggier',
        email: 'hruggier1a@g.co',
        gender: 'Male',
        Occupation: 'Product Engineer',
        favorite: 'Fuscia',
        ip_address: '87.104.44.87',
    },
    {
        id: 48,
        name: 'Robinett Worthington',
        email: 'rworthington1b@wikispaces.com',
        gender: 'Female',
        Occupation: 'Nurse Practicioner',
        favorite: 'Khaki',
        ip_address: '125.253.236.238',
    },
    {
        id: 49,
        name: 'Georgy Petriello',
        email: 'gpetriello1c@symantec.com',
        gender: 'Agender',
        Occupation: 'Biostatistician I',
        favorite: 'Purple',
        ip_address: '242.227.170.115',
    },
    {
        id: 50,
        name: 'Susette Kenningham',
        email: 'skenningham1d@indiatimes.com',
        gender: 'Female',
        Occupation: 'Statistician IV',
        favorite: 'Indigo',
        ip_address: '34.211.193.85',
    },
    {
        id: 51,
        name: 'Jarid Wettern',
        email: 'jwettern1e@bbc.co.uk',
        gender: 'Male',
        Occupation: 'Speech Pathologist',
        favorite: 'Crimson',
        ip_address: '23.226.16.154',
    },
    {
        id: 52,
        name: 'Sammie Lillow',
        email: 'slillow1f@washingtonpost.com',
        gender: 'Male',
        Occupation: 'Staff Scientist',
        favorite: 'Green',
        ip_address: '77.209.196.92',
    },
    {
        id: 53,
        name: 'Horatio Snape',
        email: 'hsnape1g@typepad.com',
        gender: 'Male',
        Occupation: 'Librarian',
        favorite: 'Pink',
        ip_address: '212.155.199.244',
    },
    {
        id: 54,
        name: 'Maddy Wiltshier',
        email: 'mwiltshier1h@360.cn',
        gender: 'Female',
        Occupation: 'Nurse Practicioner',
        favorite: 'Puce',
        ip_address: '225.216.56.113',
    },
    {
        id: 55,
        name: 'Vittorio Fatscher',
        email: 'vfatscher1i@shinystat.com',
        gender: 'Male',
        Occupation: 'Environmental Tech',
        favorite: 'Purple',
        ip_address: '72.27.178.162',
    },
    {
        id: 56,
        name: 'Daniela Budget',
        email: 'dbudget1j@addthis.com',
        gender: 'Female',
        Occupation: 'Compensation Analyst',
        favorite: 'Crimson',
        ip_address: '103.199.101.197',
    },
    {
        id: 57,
        name: 'Madison Ferrarone',
        email: 'mferrarone1k@csmonitor.com',
        gender: 'Male',
        Occupation: 'Senior Sales Associate',
        favorite: 'Violet',
        ip_address: '102.81.191.113',
    },
    {
        id: 58,
        name: 'Chevalier Lombardo',
        email: 'clombardo1l@ed.gov',
        gender: 'Male',
        Occupation: 'Technical Writer',
        favorite: 'Teal',
        ip_address: '30.172.240.252',
    },
    {
        id: 59,
        name: 'Elianore Barlass',
        email: 'ebarlass1m@google.co.jp',
        gender: 'Female',
        Occupation: 'Statistician IV',
        favorite: 'Maroon',
        ip_address: '131.76.155.157',
    },
    {
        id: 60,
        name: 'Norby Streatfield',
        email: 'nstreatfield1n@businessweek.com',
        gender: 'Male',
        Occupation: 'Nuclear Power Engineer',
        favorite: 'Teal',
        ip_address: '100.0.15.33',
    },
    {
        id: 61,
        name: 'Grier Haistwell',
        email: 'ghaistwell1o@e-recht24.de',
        gender: 'Female',
        Occupation: 'Business Systems Development Analyst',
        favorite: 'Red',
        ip_address: '53.147.51.192',
    },
    {
        id: 62,
        name: 'Levy Friel',
        email: 'lfriel1p@cafepress.com',
        gender: 'Male',
        Occupation: 'Cost Accountant',
        favorite: 'Blue',
        ip_address: '239.26.176.186',
    },
    {
        id: 63,
        name: 'Bill Keenor',
        email: 'bkeenor1q@comsenz.com',
        gender: 'Female',
        Occupation: 'Environmental Tech',
        favorite: 'Teal',
        ip_address: '237.73.100.100',
    },
    {
        id: 64,
        name: 'Normy Jorez',
        email: 'njorez1r@nationalgeographic.com',
        gender: 'Male',
        Occupation: 'General Manager',
        favorite: 'Puce',
        ip_address: '141.1.209.6',
    },
    {
        id: 65,
        name: 'Dilan Andre',
        email: 'dandre1s@hud.gov',
        gender: 'Male',
        Occupation: 'Internal Auditor',
        favorite: 'Fuscia',
        ip_address: '118.213.182.166',
    },
    {
        id: 66,
        name: 'Chantalle Reame',
        email: 'creame1t@domainmarket.com',
        gender: 'Female',
        Occupation: 'Senior Financial Analyst',
        favorite: 'Violet',
        ip_address: '120.45.255.252',
    },
    {
        id: 67,
        name: 'Sylas Gouthier',
        email: 'sgouthier1u@printfriendly.com',
        gender: 'Male',
        Occupation: 'Statistician III',
        favorite: 'Purple',
        ip_address: '10.185.97.115',
    },
    {
        id: 68,
        name: 'Brent Cresser',
        email: 'bcresser1v@kickstarter.com',
        gender: 'Male',
        Occupation: 'Office Assistant II',
        favorite: 'Fuscia',
        ip_address: '53.162.182.153',
    },
    {
        id: 69,
        name: 'Joshuah Spinage',
        email: 'jspinage1w@fastcompany.com',
        gender: 'Male',
        Occupation: 'Systems Administrator IV',
        favorite: 'Purple',
        ip_address: '219.120.7.119',
    },
    {
        id: 70,
        name: 'Evita Stower',
        email: 'estower1x@google.pl',
        gender: 'Female',
        Occupation: 'Director of Sales',
        favorite: 'Yellow',
        ip_address: '243.21.211.119',
    },
    {
        id: 71,
        name: 'Jourdan McPhilip',
        email: 'jmcphilip1y@issuu.com',
        gender: 'Female',
        Occupation: 'Geological Engineer',
        favorite: 'Indigo',
        ip_address: '230.249.235.248',
    },
    {
        id: 72,
        name: 'Filmore Le Marquand',
        email: 'fle1z@rakuten.co.jp',
        gender: 'Male',
        Occupation: 'Automation Specialist III',
        favorite: 'Goldenrod',
        ip_address: '135.184.140.218',
    },
    {
        id: 73,
        name: 'Carleton Foli',
        email: 'cfoli20@java.com',
        gender: 'Male',
        Occupation: 'Editor',
        favorite: 'Khaki',
        ip_address: '67.109.83.161',
    },
    {
        id: 74,
        name: 'Ashbey Saby',
        email: 'asaby21@delicious.com',
        gender: 'Male',
        Occupation: 'Librarian',
        favorite: 'Turquoise',
        ip_address: '121.165.145.1',
    },
    {
        id: 75,
        name: 'Odelia Jacobssen',
        email: 'ojacobssen22@hhs.gov',
        gender: 'Female',
        Occupation: 'Graphic Designer',
        favorite: 'Maroon',
        ip_address: '166.143.10.255',
    },
    {
        id: 76,
        name: 'Maddalena Stokell',
        email: 'mstokell23@taobao.com',
        gender: 'Female',
        Occupation: 'Quality Control Specialist',
        favorite: 'Crimson',
        ip_address: '32.63.185.176',
    },
    {
        id: 77,
        name: 'Sile Ginity',
        email: 'sginity24@parallels.com',
        gender: 'Female',
        Occupation: 'Registered Nurse',
        favorite: 'Aquamarine',
        ip_address: '90.156.190.117',
    },
    {
        id: 78,
        name: 'Cleavland Fawlkes',
        email: 'cfawlkes25@icio.us',
        gender: 'Male',
        Occupation: 'Occupational Therapist',
        favorite: 'Pink',
        ip_address: '59.103.241.245',
    },
    {
        id: 79,
        name: 'Sanders Pregal',
        email: 'spregal26@ifeng.com',
        gender: 'Male',
        Occupation: 'Assistant Professor',
        favorite: 'Blue',
        ip_address: '140.226.47.103',
    },
    {
        id: 80,
        name: 'Fey De Anesy',
        email: 'fde27@themeforest.net',
        gender: 'Female',
        Occupation: 'Mechanical Systems Engineer',
        favorite: 'Yellow',
        ip_address: '235.172.55.159',
    },
    {
        id: 81,
        name: 'Neely Gowling',
        email: 'ngowling28@wisc.edu',
        gender: 'Female',
        Occupation: 'Budget/Accounting Analyst II',
        favorite: 'Purple',
        ip_address: '6.187.193.104',
    },
    {
        id: 82,
        name: 'Nessa Farren',
        email: 'nfarren29@ebay.com',
        gender: 'Genderfluid',
        Occupation: 'Actuary',
        favorite: 'Goldenrod',
        ip_address: '210.43.125.210',
    },
    {
        id: 83,
        name: 'Dorrie Crosen',
        email: 'dcrosen2a@soup.io',
        gender: 'Female',
        Occupation: 'Senior Developer',
        favorite: 'Blue',
        ip_address: '46.55.215.152',
    },
    {
        id: 84,
        name: 'Sydel Riggott',
        email: 'sriggott2b@mtv.com',
        gender: 'Female',
        Occupation: 'Senior Developer',
        favorite: 'Teal',
        ip_address: '212.93.209.92',
    },
    {
        id: 85,
        name: 'Phil McAulay',
        email: 'pmcaulay2c@rambler.ru',
        gender: 'Male',
        Occupation: 'Statistician II',
        favorite: 'Yellow',
        ip_address: '55.183.231.214',
    },
    {
        id: 86,
        name: 'Clair Djurdjevic',
        email: 'cdjurdjevic2d@ucla.edu',
        gender: 'Male',
        Occupation: 'Community Outreach Specialist',
        favorite: 'Maroon',
        ip_address: '124.25.174.218',
    },
    {
        id: 87,
        name: 'Madalyn Cauldwell',
        email: 'mcauldwell2e@weebly.com',
        gender: 'Agender',
        Occupation: 'Mechanical Systems Engineer',
        favorite: 'Red',
        ip_address: '103.16.230.49',
    },
    {
        id: 88,
        name: 'Tabbie Sneyd',
        email: 'tsneyd2f@patch.com',
        gender: 'Male',
        Occupation: 'Payment Adjustment Coordinator',
        favorite: 'Blue',
        ip_address: '128.203.159.212',
    },
    {
        id: 89,
        name: 'Isabella Comoletti',
        email: 'icomoletti2g@e-recht24.de',
        gender: 'Female',
        Occupation: 'Administrative Officer',
        favorite: 'Crimson',
        ip_address: '189.137.61.59',
    },
    {
        id: 90,
        name: 'Ashley Hylands',
        email: 'ahylands2h@imgur.com',
        gender: 'Female',
        Occupation: 'Human Resources Manager',
        favorite: 'Purple',
        ip_address: '95.146.110.191',
    },
    {
        id: 91,
        name: 'Marco Kett',
        email: 'mkett2i@vistaprint.com',
        gender: 'Male',
        Occupation: 'Nurse Practicioner',
        favorite: 'Violet',
        ip_address: '250.238.239.164',
    },
    {
        id: 92,
        name: 'Kimberly Gildroy',
        email: 'kgildroy2j@springer.com',
        gender: 'Female',
        Occupation: 'Civil Engineer',
        favorite: 'Aquamarine',
        ip_address: '171.172.99.163',
    },
    {
        id: 93,
        name: 'Lorrie Jone',
        email: 'ljone2k@howstuffworks.com',
        gender: 'Non-binary',
        Occupation: 'Nuclear Power Engineer',
        favorite: 'Teal',
        ip_address: '202.78.73.192',
    },
    {
        id: 94,
        name: 'Kilian Prout',
        email: 'kprout2l@kickstarter.com',
        gender: 'Male',
        Occupation: 'Quality Control Specialist',
        favorite: 'Khaki',
        ip_address: '178.217.149.141',
    },
    {
        id: 95,
        name: 'Caryl Goldthorpe',
        email: 'cgoldthorpe2m@devhub.com',
        gender: 'Female',
        Occupation: 'Senior Editor',
        favorite: 'Turquoise',
        ip_address: '133.193.170.205',
    },
    {
        id: 96,
        name: 'Frasco Dormer',
        email: 'fdormer2n@ebay.com',
        gender: 'Male',
        Occupation: 'Social Worker',
        favorite: 'Fuscia',
        ip_address: '177.196.157.76',
    },
    {
        id: 97,
        name: 'Borg Norvill',
        email: 'bnorvill2o@cmu.edu',
        gender: 'Male',
        Occupation: 'Media Manager III',
        favorite: 'Yellow',
        ip_address: '37.110.176.37',
    },
    {
        id: 98,
        name: 'Johna Stuckes',
        email: 'jstuckes2p@yandex.ru',
        gender: 'Female',
        Occupation: 'Graphic Designer',
        favorite: 'Yellow',
        ip_address: '187.131.146.142',
    },
    {
        id: 99,
        name: 'Matthias Sails',
        email: 'msails2q@google.com.br',
        gender: 'Male',
        Occupation: 'Electrical Engineer',
        favorite: 'Aquamarine',
        ip_address: '179.87.103.51',
    },
    {
        id: 100,
        name: 'Seumas Skippen',
        email: 'sskippen2r@barnesandnoble.com',
        gender: 'Male',
        Occupation: 'Graphic Designer',
        favorite: 'Mauv',
        ip_address: '146.102.217.173',
    },
];
